version: "3"
services:
    nest-shop:
        container_name: nest-shop
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3000:3000"
